[build]
  publish = "build"
  command = "npm run build && npm run postbuild"   # see step 5

[[headers]]
  for = "/*"
    [headers.values]
      Content-Security-Policy = "default-src 'self'; img-src * data:;"
      X-Frame-Options        = "DENY"
      X-Content-Type-Options = "nosniff"
      Referrer-Policy        = "strict-origin-when-cross-origin"
      Cache-Control          = "public, max-age=31536000, immutable"

[[redirects]]
  from = "http://lilleyjakub.com/*"
  to   = "https://lilleyjakub.com/:splat"
  status = 301
  force  = true